$schema: http://json-schema.org/draft/2020-12/schema
properties:
  format:
    properties:
      bit_rate:
        type: string
      duration:
        type: string
      filename:
        type: string
      format_long_name:
        type: string
      format_name:
        type: string
      nb_programs:
        type: integer
      nb_streams:
        type: integer
      probe_score:
        type: integer
      size:
        type: string
      start_time:
        type: string
      tags:
        properties:
          ARTIST:
            type: string
          COM.APPLE.QUICKTIME.AUTHOR:
            type: string
          COM.APPLE.QUICKTIME.DESCRIPTION:
            type: string
          COM.APPLE.QUICKTIME.DISPLAYNAME:
            type: string
          COM.APPLE.QUICKTIME.KEYWORDS:
            type: string
          COM.APPLE.QUICKTIME.TITLE:
            type: string
          COMMENT:
            type: string
          COMPATIBLE_BRANDS:
            type: string
          DATE:
            type: string
          DESCRIPTION:
            type: string
          ENCODER:
            type: string
          FILE:
            type: string
          Hw:
            type: string
          KEYWORDS:
            type: string
          MAJOR_BRAND:
            type: string
          MINOR_VERSION:
            type: string
          PURL:
            type: string
          SCENE:
            type: string
          SYNOPSIS:
            type: string
          TIMECODE:
            type: string
          Writing frontend:
            type: string
          artist:
            type: string
          audiodelay:
            type: string
          bitrate:
            type: string
          canSeekToEnd:
            type: string
          com.android.capture.fps:
            type: string
          com.android.version:
            type: string
          com.apple.quicktime.author:
            type: string
          com.apple.quicktime.description:
            type: string
          com.apple.quicktime.displayname:
            type: string
          com.apple.quicktime.keywords:
            type: string
          com.apple.quicktime.title:
            type: string
          comment:
            type: string
          compatible_brands:
            type: string
          composer:
            type: string
          creation_time:
            anyOf:
              - type: string
              - format: date-time
                type: string
          creationdate:
            type: string
          date:
            type: string
          description:
            type: string
          encoder:
            type: string
          encoder-eng:
            type: string
          episode_sort:
            type: string
          hd_video:
            type: string
          iTunMOVI:
            type: string
          location:
            type: string
          major_brand:
            type: string
          maxrate:
            type: string
          media_type:
            type: string
          minor_version:
            type: string
          modification_time:
            format: date-time
            type: string
          season_number:
            type: string
          software:
            type: string
          synopsis:
            type: string
          te_is_reencode:
            type: string
          title:
            type: string
        type: object
    required:
      - bit_rate
      - duration
      - filename
      - format_long_name
      - format_name
      - nb_programs
      - nb_streams
      - probe_score
      - size
    type: object
  streams:
    items:
      properties:
        avg_frame_rate:
          type: string
        bit_rate:
          type: string
        bits_per_raw_sample:
          type: string
        bits_per_sample:
          type: integer
        channel_layout:
          type: string
        channels:
          type: integer
        chroma_location:
          type: string
        closed_captions:
          type: integer
        codec_long_name:
          type: string
        codec_name:
          type: string
        codec_tag:
          type: string
        codec_tag_string:
          type: string
        codec_type:
          type: string
        coded_height:
          type: integer
        coded_width:
          type: integer
        color_primaries:
          type: string
        color_range:
          type: string
        color_space:
          type: string
        color_transfer:
          type: string
        display_aspect_ratio:
          type: string
        disposition:
          properties:
            attached_pic:
              type: integer
            captions:
              type: integer
            clean_effects:
              type: integer
            comment:
              type: integer
            default:
              type: integer
            dependent:
              type: integer
            descriptions:
              type: integer
            dub:
              type: integer
            forced:
              type: integer
            hearing_impaired:
              type: integer
            karaoke:
              type: integer
            lyrics:
              type: integer
            metadata:
              type: integer
            non_diegetic:
              type: integer
            original:
              type: integer
            still_image:
              type: integer
            timed_thumbnails:
              type: integer
            visual_impaired:
              type: integer
          required:
            - attached_pic
            - captions
            - clean_effects
            - comment
            - default
            - dependent
            - descriptions
            - dub
            - forced
            - hearing_impaired
            - karaoke
            - lyrics
            - metadata
            - non_diegetic
            - original
            - still_image
            - timed_thumbnails
            - visual_impaired
          type: object
        divx_packed:
          type: string
        duration:
          type: string
        duration_ts:
          type: integer
        extradata_size:
          type: integer
        field_order:
          type: string
        film_grain:
          type: integer
        has_b_frames:
          type: integer
        height:
          type: integer
        id:
          type: string
        index:
          type: integer
        initial_padding:
          type: integer
        is_avc:
          type: string
        level:
          type: integer
        missing_streams:
          type: string
        nal_length_size:
          type: string
        nb_frames:
          type: string
        pix_fmt:
          type: string
        profile:
          type: string
        quarter_sample:
          type: string
        r_frame_rate:
          type: string
        refs:
          type: integer
        sample_aspect_ratio:
          type: string
        sample_fmt:
          type: string
        sample_rate:
          type: string
        side_data_list:
          items:
            properties:
              avg_bitrate:
                type: integer
              buffer_size:
                type: integer
              displaymatrix:
                type: string
              inverted:
                type: integer
              max_bitrate:
                type: integer
              min_bitrate:
                type: integer
              pitch:
                type: integer
              projection:
                type: string
              roll:
                type: integer
              rotation:
                type: integer
              service_type:
                type: integer
              side_data_type:
                type: string
              type:
                type: string
              vbv_delay:
                type: integer
              yaw:
                type: integer
            required:
              - side_data_type
            type: object
          type: array
        start_pts:
          type: integer
        start_time:
          type: string
        tags:
          properties:
            BPS:
              type: string
            BPS-eng:
              type: string
            DURATION:
              type: string
            DURATION-eng:
              type: string
            ENCODER:
              type: string
            HANDLER_NAME:
              type: string
            NUMBER_OF_BYTES:
              type: string
            NUMBER_OF_BYTES-eng:
              type: string
            NUMBER_OF_FRAMES:
              type: string
            NUMBER_OF_FRAMES-eng:
              type: string
            SOURCE_ID:
              type: string
            SOURCE_ID-eng:
              type: string
            TIMECODE:
              type: string
            VENDOR_ID:
              type: string
            _STATISTICS_TAGS:
              type: string
            _STATISTICS_TAGS-eng:
              type: string
            _STATISTICS_WRITING_APP:
              type: string
            _STATISTICS_WRITING_APP-eng:
              type: string
            _STATISTICS_WRITING_DATE_UTC:
              type: string
            _STATISTICS_WRITING_DATE_UTC-eng:
              type: string
            alpha_mode:
              type: string
            creation_time:
              format: date-time
              type: string
            encoder:
              type: string
            filename:
              type: string
            handler_name:
              type: string
            language:
              type: string
            mimetype:
              type: string
            timecode:
              type: string
            title:
              type: string
            vendor_id:
              type: string
          type: object
        time_base:
          type: string
        width:
          type: integer
      required:
        - avg_frame_rate
        - codec_tag
        - codec_tag_string
        - codec_type
        - disposition
        - index
        - r_frame_rate
        - time_base
      type: object
    type: array
type: object
